export const useInitialValues = (props) => {
  return {
    REASON_OF_DELETE: "",
    DELETE_DATE: "",
    CR_ISSUANCE_AUTHORITY: "",
    PROJECT_DURATION: "",
    PROJECT_LEASE_START_DATE:"",
    MAXIMUM_CEILING_AMOUNT:"",
    REGISTRATION_ISSUER:"",
    STATEMENT_LANGUAGE:"",
    PRIMARY_LANGUAGE:"",
    ENTITY_NATIONALITY:"",
    COMMERCIAL_NAME_LINE_2_E:"",
    COMMERCIAL_NAME_LINE_1_E:"",
    COMMERCIAL_NAME_LINE_2_A:"",
    COMMERCIAL_NAME_LINE_1_A:""
  };
};
